version: "3.7"

x-app-config: &app-config
  DJANGO_ENV: dev
  DJANGO_SECRET_KEY: secret_key

x-db-config: &db-config
  DATABASE_NAME: postgres
  DATABASE_USER: postgres
  DATABASE_PASSWORD: pgpassword
  DATABASE_HOST: db
  DATABASE_PORT: 5432
  POSTGRES_PASSWORD: pgpassword
  EMAIL_USE_SSL: 1
  EMAIL_USE_TLS: 1
  EMAIL_HOST: smtp.gmail.com
  EMAIL_HOST_USER: username
  EMAIL_HOST_PASSWORD: password
  EMAIL_PORT: 465

services:
  api:
    image: userapp_api
    build:
      context: .
    environment:
      <<: *app-config
      <<: *db-config
    depends_on:
      - db
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true

  db:
    image: postgres:14.8
    environment: *db-config
    logging:
      driver: none
    ports:
      - "5432:5432"

volumes:
  sqlvolume: