version: "3.7"

x-app-config: &app-config
  DJANGO_ENV: dev
  DJANGO_SECRET_KEY: secret_key

x-db-config: &db-config
  DATABASE_NAME: postgres
  DATABASE_USER: postgres
  DATABASE_PASSWORD: pgpassword
  DATABASE_HOST: db
  DATABASE_PORT: 5432
  POSTGRES_PASSWORD: pgpassword
  EMAIL_USE_SSL: 1
  EMAIL_USE_TLS: 1
  EMAIL_HOST: smtp.gmail.com
  EMAIL_HOST_USER: username
  EMAIL_HOST_PASSWORD: password
  EMAIL_PORT: 465
  REDIS_HOST: redis
  REDIS_PORT: 6379

services:
  api:
    image: userapp_api
    build:
      context: .
    environment:
      <<: *app-config
      <<: *db-config
    depends_on:
      - db
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true

  db:
    image: postgres:14.8
    environment: *db-config
    logging:
      driver: none
    ports:
      - "5432:5432"

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery --app=task_manager worker --loglevel=info
    environment:
      <<: *app-config
    volumes: 
      - .:/app
    depends_on:
      - redis
    
  flower:
    build: .
    command: celery --app=task_manager --broker=redis://redis:6379/0 flower --port=5555
    environment:
      <<: *app-config
    volumes: 
      - .:/app
    ports:
      - "5555:5555"
    depends_on:
      - redis  

volumes:
  sqlvolume: