# Generated by Django 4.2.2 on 2023-07-12 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('developer', 'Developer'), ('manager', 'Manager'), ('admin', 'Admin')], default='developer', max_length=255),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_changed', models.DateTimeField(auto_now=True)),
                ('final_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new_task', 'New Task'), ('in_development', 'In Develoment'), ('archived', 'Archived'), ('in_qa', 'In Qa'), ('in_code_review', 'In Code Review'), ('ready_fore_release', 'Ready For Release'), ('released', 'Released')], default='new_task', max_length=255)),
                ('priority', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='performer', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='main.tag')),
            ],
        ),
    ]
