name: Main

on:
  pull_request:
    branches:
      - 'develop'
      - 'feature/**'
  push:
    branches:
      - 'develop'
      - 'feature/**'

env:
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v1
      - name: Run tests
        env:
          COVERAGE: true
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          DJANGO_ENV: test
        run: docker-compose --file docker-compose.ci.yml run --rm api make test

      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@develop

  coveralls_finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop