name: Main

on:
  pull_request:
    branches:
      - 'develop'
      - 'feature/**'
  push:
    branches:
      - 'develop'
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: DB Environment
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v1
      - name: Run tests
        env:
          COVERAGE: true
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: docker-compose --file docker-compose.ci.yml run --rm api make test